Portal3/Controllers/Users1CController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Portal3.Models;
using System.Data.SqlClient;
using System.Configuration;

namespace Portal3.Controllers
{
    public class Users1CController : Controller
    {
        PrognozEDWEntities db = new PrognozEDWEntities();
        SalesEntities db2 = new SalesEntities();

        // GET: Users1C
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ShowUsers(string submitButton, string searchString, string RUfirstname, string RUlastame, string ENfirstname,
            string ENlastname, string domainname, string mail, string idsprav, string id1c, string idcrm, string staffcode, string empdate, string kickdate)
        {
            switch (submitButton)
            {
                case "Map":
                    {
                        if (RUfirstname != "" && RUlastame != "" && ENfirstname != "" &&
                    ENlastname != "" && domainname != "" && mail != "")
                        {
                            try
                            {
                                #region -1 param

                                if (idsprav == "")
                                    idsprav = "-1";

                                if (id1c == "")
                                    id1c = "-1";

                                if (idcrm == "")
                                    idcrm = "-1";

                                #endregion

                                db2.MapUser(RUfirstname, RUlastame, ENfirstname, ENlastname, domainname, mail,
                                    Convert.ToInt32(idsprav), Convert.ToInt32(id1c), idcrm, staffcode, empdate, kickdate);
                            }
                            catch (Exception ex)
                            {
                                return PartialView(ex);
                            }
                        }

                        return PartialView();
                    };

                case "Search":
                    {
                        if (searchString != null)
                        {
                            CobinedUserList model = new CobinedUserList();
                            List<string> mappedlist = MapperFuncs.MapRUEN(searchString);
                            string request = ";";

                            foreach (string mappedres in mappedlist)
                                request += mappedres + ";";

                            model.list1C = db.FindUsers1C(searchString).ToList();
                            model.listCRM = db.FindUsersCRM(request).ToList();
                            model.listSpr = db2.FindSpr(searchString).ToList();

                            return PartialView(model);
                        }
                        return PartialView();
                    }
                default:
                    {
                        return PartialView();
                    }
            }
        }
        //private void MapUser(string nameru, string famru, string nameen, string famen, string domain, string mail,string id, string id1c, string idcrm, string staff, string empdate, string dismiss)
        //{
        //    SqlConnection connection = new SqlConnection("metadata=res://*/Models.SalesModel.csdl|res://*/Models.SalesModel.ssdl|res://*/Models.SalesModel.msl;provider=System.Data.SqlClient;provider connection string=&quot;data source=msk02drkp02;initial catalog=Sales;integrated security=True;MultipleActiveResultSets=True;App=EntityFramework&quot;");
        //    string sqlExpression = "MapUserUpd";
        //    connection.Open();

        //    SqlCommand command = new SqlCommand(sqlExpression, connection);
        //    command.CommandType = System.Data.CommandType.StoredProcedure;

        //    #region Params

        //    SqlParameter nameruParam = new SqlParameter
        //    {
        //        ParameterName = "@FirstNameRU",
        //        Value = nameru
        //    };
        //    command.Parameters.Add(nameruParam);

        //    SqlParameter famruParam = new SqlParameter
        //    {
        //        ParameterName = "@LastNameRU",
        //        Value = famru
        //    };
        //    command.Parameters.Add(famruParam);

        //    SqlParameter nameenParam = new SqlParameter
        //    {
        //        ParameterName = "@FirstNameEn",
        //        Value = nameen
        //    };
        //    command.Parameters.Add(nameenParam);

        //    SqlParameter famenParam = new SqlParameter
        //    {
        //        ParameterName = "@LastNameEn ",
        //        Value = famen
        //    };
        //    command.Parameters.Add(famenParam);

        //    SqlParameter domainParam = new SqlParameter
        //    {
        //        ParameterName = "@DomainName ",
        //        Value = domain
        //    };
        //    command.Parameters.Add(domainParam);

        //    SqlParameter mailParam = new SqlParameter
        //    {
        //        ParameterName = "@Mail",
        //        Value = mail
        //    };
        //    command.Parameters.Add(mailParam);
        //    if (id != "")
        //    {
        //        SqlParameter useridParam = new SqlParameter
        //        {
        //            ParameterName = "@userID",
        //            Value = id
        //        };
        //        command.Parameters.Add(useridParam);
        //    }
        //    else
        //    {
        //        SqlParameter useridParam = new SqlParameter
        //        {
        //            ParameterName = "@userID",
        //            Value = "-1"
        //        };
        //        command.Parameters.Add(useridParam);
        //    }
        //    if (id1c == "")
        //    {
        //        SqlParameter id1cParam = new SqlParameter
        //        {
        //            ParameterName = "@ID1C",
        //            Value = "-1"
        //        };
        //        command.Parameters.Add(id1cParam);
        //    }
        //    else
        //    {
        //        SqlParameter id1cParam = new SqlParameter
        //        {
        //            ParameterName = "@ID1C",
        //            Value = id1c
        //        };
        //        command.Parameters.Add(id1cParam);
        //    }

        //    if (idcrm == "")
        //    {
        //        SqlParameter idcrmParam = new SqlParameter
        //        {
        //            ParameterName = "@IDCRM",
        //            Value = "-1"
        //        };
        //        command.Parameters.Add(idcrmParam);
        //    }
        //    else
        //    {
        //        SqlParameter idcrmParam = new SqlParameter
        //        {
        //            ParameterName = "@IDCRM",
        //            Value = idcrm
        //        };
        //        command.Parameters.Add(idcrmParam);
        //    }
        //    SqlParameter staffParam = new SqlParameter
        //    {
        //        ParameterName = "@StaffCode",
        //        Value = staff
        //    };
        //    command.Parameters.Add(staffParam);
        //    SqlParameter empdateParam = new SqlParameter
        //    {
        //        ParameterName = "@EmpDate",
        //        Value = empdate
        //    };
        //    command.Parameters.Add(empdateParam);
        //    SqlParameter dismissParam = new SqlParameter
        //    {
        //        ParameterName = "@dismissDate",
        //        Value = dismiss
        //    };
        //    command.Parameters.Add(dismissParam);

        //    #endregion

        //    command.ExecuteNonQuery();
        //}

        // GET: Users1C/Details/5
    }
}

Portal3/Views/Users1C/Index.cshtml
@using (Html.BeginForm())
{
    <p>
        Find by name: @Html.TextBox("SearchString")
        @Html.ActionLink("Search", "ShowUsers", "Users1C")
    </p>
}

Portal3/Views/Users1C/ShowUsers.cshtml
@using Portal3.Models; 

@model Portal3.Models.CobinedUserList

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<style>
    table, th, td {
        border: 1px solid black;
        background-color: white;
        padding-left:5px;
        margin-left: auto;
        margin-right: auto;
        height: 25%;
    }
    p {
        height:10px;
    }

    #left {
      float: left;
      width: 20%;
      overflow: hidden;
      margin-left:10px;
      margin-right:10px;
    }

    #right {
        width: 75%;
        overflow: hidden;
    }
    input.inputbox {
        float:right;
    }
    #table1c{
        height:25vh;
        overflow-y: scroll;
        float:left;
        margin-bottom:10px;
    }
    #tablecrm{
        height:25vh;
        overflow-y: scroll;
        float:left;
        margin-bottom:10px;
    }
    #tablespr{
        height:25vh;
        overflow-y: scroll;
        float:left;
        margin-bottom:15px;
    }
</style>

<script>
    function handleCRMChose(element, id, name, surname, domainname, mail)
    {
        document.getElementById('idcrm').value = id;
        document.getElementById('ENfirstname').value = name;
        document.getElementById('ENlastname').value = surname;
        document.getElementById('domainname').value = domainname;
        document.getElementById('mail').value = mail;

    }

    function handle1CChose(element, id, name, surname)
    {
        document.getElementById('id1c').value = id;
        document.getElementById('RUfirstname').value = name;
        document.getElementById('RUlastame').value = surname;
    }

    function handleSprChose(element, id)
    {
        document.getElementById('idsprav').value = id;
        document.getElementById('idsprav').readOnly = true;
    }

</script>

@using (Html.BeginForm())
{
    <div id="left">
        Имя или его часть @Html.TextBox("SearchString")
        <input type="submit" name="submitButton" value="Search" />
        
        <p></p>
        
        ИмяRU
        @Html.TextBox("RUfirstname", null, new { @class = "inputbox" })
        
        <p></p>
        
        ФамилияRU
        @Html.TextBox("RUlastame", null, new { @class = "inputbox" })
        
        <p></p>
        
        ИмяEN
        @Html.TextBox("ENfirstname", null, new { @class = "inputbox" })
        
        <p></p>
        
        ФамилияEn
        @Html.TextBox("ENlastname", null, new { @class = "inputbox" })
        
        <p></p>
        
        Доменное Имя
        @Html.TextBox("domainname", null, new { @class = "inputbox" })
        
        <p></p>
        
        Электронная почта
        @Html.TextBox("mail", null, new { @class = "inputbox" })
        
        <p></p>
        
        ID в 1С
        @Html.TextBox("id1c", null, new { @class = "inputbox" })
        
        <p></p>
        
        ID в CRM
        @Html.TextBox("idcrm", null, new { @class = "inputbox" })
        
        <p></p>
        
        ID в Справочнике
        @Html.TextBox("idsprav", null, new { @class = "inputbox" })
        
        <p></p>

        <input type="submit" name="submitButton" value="Map" />
             
        @*Стаф Код
        @Html.TextBox("staffcode", null, new { @class = "inputbox" })
        <p></p>
        Дата выхода
        @Html.TextBox("empdate", null, new { @class = "inputbox" })
        <p></p>
        Дата увольнения
        @Html.TextBox("kickdate", null, new { @class = "inputbox" })*@

    </div>
    
    <div id="right">

        @if (Model != null)
        {
            <p></p>

            <div id="tablecrm">

                <div style="text-align:center;">CRM Пользователи</div>

                <table>
                    <tr>
                        <td>     </td>
                        <td>SysUIDCRM</td>
                        <td>SysUFullName</td>
                        <td>Parent</td>
                        <td>Otdel</td>
                        <td>DomainName</td>
                        <td>EMailAddress</td>

                    </tr>

                    @foreach (UserCRM user in Model.listCRM)
                    {
                        <tr>
                            <td>@Html.RadioButtonFor(m => m.listCRM, "", new { onchange = "handleCRMChose(this, '" + user.SysUIDCRM +
                               "', '"+ user.SysUFirstName + "', '" + user.SysULastName + "', '" + user.DomainName.doubleslash() +
                               "', '" + user.EMailAddress + "')" })</td>
                            <td>@user.SysUIDCRM</td>
                            <td>@user.SysUFullName</td>
                            <td>@user.Parent</td>
                            <td>@user.Otdel</td>
                            <td>@user.DomainName</td>
                            <td>@user.EMailAddress</td>
                        </tr>
                    }
                </table>
            </div>
            
            <p></p>

            <div id="table1c">
                <div style="text-align:center;">1C Пользователи</div>

                <table>
                    <tr>
                        <td>     </td>
                        <td>User_ID</td>
                        <td>User_Name</td>
                        <td>Parent</td>
                        <td>Sub_Name</td>
                    </tr>

                    @foreach (User1C user in Model.list1C)
                    {
                        <tr>
                            <td>@Html.RadioButtonFor(m => m.list1C, "", new { onchange = "handle1CChose(this, '" + user.User_ID + "', '" + 
                               user.User_Name.GetFirstName() + "', '" + user.User_Name.GetLastName() + "')"})</td>
                            <td>@user.User_ID</td>
                            <td>@user.User_Name</td>
                            <td>@user.Parent</td>
                            <td>@user.Sub_Name</td>
                        </tr>
                    }

                </table>
            </div>

            <p></p>

            <div id="tablespr">
                <div style="text-align:center;">Пользователи из справочника</div>

                <table>
                    <tr>
                        <td>     </td>
                        <td>ID</td>
                        <td>FullNameRU</td>
                        <td>DomainName</td>
                        <td>EmailAdress</td>
                    </tr>

                    @foreach (UserSpr user in Model.listSpr)
                    {
                        <tr>
                            <td>
                                @Html.RadioButtonFor(m => m.listSpr, "", new { onchange = "handleSprChose(this, '" + user.ID + "')" })
                        </td>
                        <td>@user.ID</td>
                        <td>@user.FullNameRu</td>
                        <td>@user.DomainName</td>
                        <td>@user.EMailAddress</td>
                    </tr>
                    }
                </table>
            </div>
        }       
    </div>
}